export const BIRTH_COUNTRIES = {
  EUROPE: [
    { code: "FR", label: "France" },
    { code: "DE", label: "Germany" },
    { code: "IT", label: "Italy" },
    { code: "ES", label: "Spain" },
    { code: "GB", label: "United Kingdom" },
    { code: "BE", label: "Belgium" },
    { code: "NL", label: "Netherlands" },
    { code: "CH", label: "Switzerland" },
    { code: "AT", label: "Austria" },
    { code: "PT", label: "Portugal" },
    { code: "PL", label: "Poland" },
    { code: "RO", label: "Romania" },
    { code: "GR", label: "Greece" },
    { code: "SE", label: "Sweden" },
    { code: "NO", label: "Norway" },
    { code: "DK", label: "Denmark" },
    { code: "FI", label: "Finland" },
    { code: "IE", label: "Ireland" },
    { code: "CZ", label: "Czech Republic" },
    { code: "HU", label: "Hungary" },
    { code: "SK", label: "Slovakia" },
    { code: "BG", label: "Bulgaria" },
    { code: "HR", label: "Croatia" },
    { code: "SI", label: "Slovenia" },
    { code: "LT", label: "Lithuania" },
    { code: "LV", label: "Latvia" },
    { code: "EE", label: "Estonia" },
    { code: "LU", label: "Luxembourg" },
    { code: "MT", label: "Malta" },
    { code: "CY", label: "Cyprus" },
    { code: "IS", label: "Iceland" },
    { code: "AL", label: "Albania" },
    { code: "BA", label: "Bosnia and Herzegovina" },
    { code: "MK", label: "North Macedonia" },
    { code: "ME", label: "Montenegro" },
    { code: "RS", label: "Serbia" },
    { code: "UA", label: "Ukraine" },
    { code: "BY", label: "Belarus" },
    { code: "MD", label: "Moldova" },
    { code: "RU", label: "Russia" },
  ],
  AFRICA: [
    { code: "DZ", label: "Algeria" },
    { code: "AO", label: "Angola" },
    { code: "BJ", label: "Benin" },
    { code: "BW", label: "Botswana" },
    { code: "BF", label: "Burkina Faso" },
    { code: "BI", label: "Burundi" },
    { code: "CM", label: "Cameroon" },
    { code: "CV", label: "Cape Verde" },
    { code: "CF", label: "Central African Republic" },
    { code: "TD", label: "Chad" },
    { code: "KM", label: "Comoros" },
    { code: "CG", label: "Congo" },
    { code: "CD", label: "Congo (Democratic Republic)" },
    { code: "CI", label: "Côte d'Ivoire" },
    { code: "DJ", label: "Djibouti" },
    { code: "EG", label: "Egypt" },
    { code: "GQ", label: "Equatorial Guinea" },
    { code: "ER", label: "Eritrea" },
    { code: "ET", label: "Ethiopia" },
    { code: "GA", label: "Gabon" },
    { code: "GM", label: "Gambia" },
    { code: "GH", label: "Ghana" },
    { code: "GN", label: "Guinea" },
    { code: "GW", label: "Guinea-Bissau" },
    { code: "KE", label: "Kenya" },
    { code: "LS", label: "Lesotho" },
    { code: "LR", label: "Liberia" },
    { code: "LY", label: "Libya" },
    { code: "MG", label: "Madagascar" },
    { code: "MW", label: "Malawi" },
    { code: "ML", label: "Mali" },
    { code: "MR", label: "Mauritania" },
    { code: "MU", label: "Mauritius" },
    { code: "MA", label: "Morocco" },
    { code: "MZ", label: "Mozambique" },
    { code: "NA", label: "Namibia" },
    { code: "NE", label: "Niger" },
    { code: "NG", label: "Nigeria" },
    { code: "RW", label: "Rwanda" },
    { code: "ST", label: "São Tomé and Príncipe" },
    { code: "SN", label: "Senegal" },
    { code: "SC", label: "Seychelles" },
    { code: "SL", label: "Sierra Leone" },
    { code: "SO", label: "Somalia" },
    { code: "ZA", label: "South Africa" },
    { code: "SS", label: "South Sudan" },
    { code: "SD", label: "Sudan" },
    { code: "SZ", label: "Eswatini" },
    { code: "TZ", label: "Tanzania" },
    { code: "TG", label: "Togo" },
    { code: "TN", label: "Tunisia" },
    { code: "UG", label: "Uganda" },
    { code: "ZM", label: "Zambia" },
    { code: "ZW", label: "Zimbabwe" },
  ],
  ASIA: [
    { code: "AF", label: "Afghanistan" },
    { code: "AM", label: "Armenia" },
    { code: "AZ", label: "Azerbaijan" },
    { code: "BH", label: "Bahrain" },
    { code: "BD", label: "Bangladesh" },
    { code: "BT", label: "Bhutan" },
    { code: "BN", label: "Brunei" },
    { code: "KH", label: "Cambodia" },
    { code: "CN", label: "China" },
    { code: "GE", label: "Georgia" },
    { code: "IN", label: "India" },
    { code: "ID", label: "Indonesia" },
    { code: "IR", label: "Iran" },
    { code: "IQ", label: "Iraq" },
    { code: "IL", label: "Israel" },
    { code: "JP", label: "Japan" },
    { code: "JO", label: "Jordan" },
    { code: "KZ", label: "Kazakhstan" },
    { code: "KW", label: "Kuwait" },
    { code: "KG", label: "Kyrgyzstan" },
    { code: "LA", label: "Laos" },
    { code: "LB", label: "Lebanon" },
    { code: "MY", label: "Malaysia" },
    { code: "MV", label: "Maldives" },
    { code: "MN", label: "Mongolia" },
    { code: "MM", label: "Myanmar" },
    { code: "NP", label: "Nepal" },
    { code: "KP", label: "North Korea" },
    { code: "OM", label: "Oman" },
    { code: "PK", label: "Pakistan" },
    { code: "PS", label: "Palestine" },
    { code: "PH", label: "Philippines" },
    { code: "QA", label: "Qatar" },
    { code: "SA", label: "Saudi Arabia" },
    { code: "SG", label: "Singapore" },
    { code: "KR", label: "South Korea" },
    { code: "LK", label: "Sri Lanka" },
    { code: "SY", label: "Syria" },
    { code: "TW", label: "Taiwan" },
    { code: "TJ", label: "Tajikistan" },
    { code: "TH", label: "Thailand" },
    { code: "TL", label: "Timor-Leste" },
    { code: "TR", label: "Turkey" },
    { code: "TM", label: "Turkmenistan" },
    { code: "AE", label: "United Arab Emirates" },
    { code: "UZ", label: "Uzbekistan" },
    { code: "VN", label: "Vietnam" },
    { code: "YE", label: "Yemen" },
  ],
  NORTH_AMERICA: [
    { code: "US", label: "United States" },
    { code: "CA", label: "Canada" },
    { code: "MX", label: "Mexico" },
    { code: "AG", label: "Antigua and Barbuda" },
    { code: "BS", label: "Bahamas" },
    { code: "BB", label: "Barbados" },
    { code: "BZ", label: "Belize" },
    { code: "CR", label: "Costa Rica" },
    { code: "CU", label: "Cuba" },
    { code: "DM", label: "Dominica" },
    { code: "DO", label: "Dominican Republic" },
    { code: "SV", label: "El Salvador" },
    { code: "GD", label: "Grenada" },
    { code: "GT", label: "Guatemala" },
    { code: "HT", label: "Haiti" },
    { code: "HN", label: "Honduras" },
    { code: "JM", label: "Jamaica" },
    { code: "NI", label: "Nicaragua" },
    { code: "PA", label: "Panama" },
    { code: "KN", label: "Saint Kitts and Nevis" },
    { code: "LC", label: "Saint Lucia" },
    { code: "VC", label: "Saint Vincent and the Grenadines" },
    { code: "TT", label: "Trinidad and Tobago" },
  ],
  SOUTH_AMERICA: [
    { code: "AR", label: "Argentina" },
    { code: "BO", label: "Bolivia" },
    { code: "BR", label: "Brazil" },
    { code: "CL", label: "Chile" },
    { code: "CO", label: "Colombia" },
    { code: "EC", label: "Ecuador" },
    { code: "GY", label: "Guyana" },
    { code: "PY", label: "Paraguay" },
    { code: "PE", label: "Peru" },
    { code: "SR", label: "Suriname" },
    { code: "UY", label: "Uruguay" },
    { code: "VE", label: "Venezuela" },
  ],
  OCEANIA: [
    { code: "AU", label: "Australia" },
    { code: "NZ", label: "New Zealand" },
    { code: "FJ", label: "Fiji" },
    { code: "PG", label: "Papua New Guinea" },
    { code: "SB", label: "Solomon Islands" },
    { code: "VU", label: "Vanuatu" },
    { code: "WS", label: "Samoa" },
    { code: "TO", label: "Tonga" },
    { code: "KI", label: "Kiribati" },
    { code: "MH", label: "Marshall Islands" },
    { code: "FM", label: "Micronesia" },
    { code: "NR", label: "Nauru" },
    { code: "PW", label: "Palau" },
    { code: "TV", label: "Tuvalu" },
  ],
} as const;

export const ALL_BIRTH_COUNTRIES = [
  ...BIRTH_COUNTRIES.EUROPE,
  ...BIRTH_COUNTRIES.AFRICA,
  ...BIRTH_COUNTRIES.ASIA,
  ...BIRTH_COUNTRIES.NORTH_AMERICA,
  ...BIRTH_COUNTRIES.SOUTH_AMERICA,
  ...BIRTH_COUNTRIES.OCEANIA,
] as const;

export const BIRTH_COUNTRY_CODES = ALL_BIRTH_COUNTRIES.map(
  (c) => c.code
) as readonly string[];
export type BirthCountryCode = typeof ALL_BIRTH_COUNTRIES[number]["code"];
